### ISSUE TITLE
Is there a way to identify the Server Vendor type using redfish API

### ISSUE THREAD

**Issue by nagaphani23** [DMTF/python-redfish-library#71]
I am trying to identify the Server vendor type(Dell or Cisco or HP) via Redfish API which in subsequent performs tasks based on that.
I have verified "/redsfish/v1" for Cisco and Dell servers but haven't got a consistent data on identifying the server vendor type.
Is there any better way to identify the Server vendor type?

**Comment by billdodd** [comment]
The `Vendor` property in the `ServiceRoot` resource ("/redfish/v1/") is the way to get this. But this is a relatively new property (late 2018), so many existing services won't yet have it. Hopefully, you will start seeing it in more new services and in firmware updates for older services.

Here is the long description from the schema for the `Vendor` property:

> This property shall include the name of the manufacturer or vendor represented by this Redfish Service.  If this property is supported, the vendor name shall not be included in the Product property value.

**Comment by jautor** [comment]
Bill is correct, and you may be able to use (but would need to parse/scan) the `Product` property also in the `ServiceRoot`, as that property was added a year earlier.

Two things, though...  First, we're hoping to avoid the "per-vendor" scripts with the standardized data provided by Redfish - so if you're having to work around inconsistencies between vendors, we'd like to know about it (posting on www.redfishforum.com about such things is encouraged!).  But there's certainly system/vendor-specific tasks, and that's why the `Vendor` and `Product` properties were added...  

Second, if you're looking for the vendor of a server, note that because a Redfish service could represent multiple servers (such as a blade enclosure), detecting the vendor/model of each server in the \redfish\v1\Systems collection is the best way to handle all cases.  In those `ComputerSystem` resources, there is `Manufacturer` and `Model` strings which have been present since v1.0.  

Looking at those properties in the ServiceRoot will work just fine for 1U/2U servers - just note that if your fleet includes blades or other multi-node server designs, you'll want to iterate through the \redfish\v1\Systems collection to find every node.

**Comment by mraineri** [comment]
Don't forget the aggregator case; there are software based Redfish services that can present southbound systems.

**Comment by mraineri** [comment]
@nagaphani23 do the previous responses answer your question? Can we close out this issue?

**Comment by nagaphani23** [comment]
Thanks for the response and it was helpful.
I am closing the issue.
