### ISSUE TITLE
Changing the SNMP user credentials for the CISCO UCS Servers

### ISSUE THREAD

**Issue by nagaphani23** [DMTF/python-redfish-library#83]
Is there a way to change the SNMP user password for the Cisco UCS servers.
I have almost more than 50 servers and looking for a better way to do it instead of doing it manually from dashboard.
Anyone please let me know is there any way to do the same.

Regards,
Naga Phani.

**Comment by mraineri** [comment]
That really depends on whether or not Cisco supports the SNMP extensions the forum standardized on last fall.

Changes were made to the ManagerAccount resource to enable SNMP configuration, which contains a user name and password to log into the service. `AccountTypes` was added as a property, and if the array contains `SNMP`, then the account can be used to access SNMP services on the manager.

Some other schemas were updated to support SNMP configuration, but I suspect you just need to modify the ManagerAccount resources that represent SNMP accounts.

In general though, it might be worth posting this type of question on https://redfishforum.com/ since this really isn't about the Python library for Redfish, but more about general interactions with a service to accomplish an operation.

**Comment by nagaphani23** [comment]
Thanks for the info. Will check in Redfish forum as well.
